name: 'AI-based PR Reviewer & Summarizer with Chat Capabilities'
description: 'AI-based PR Reviewer & Summarizer with Chat Capabilities'
branding:
  icon: 'git-merge'
  color: 'orange'
author: 'CodeSailor LLC'
inputs:
  debug:
    required: false
    description: 'Enable debug mode'
    default: 'false'
  max_files:
    required: false
    description:
      'Max files to summarize and review. Less than or equal to 0 means no
      limit.'
    default: '150'
  review_simple_changes:
    required: false
    description: 'Review even when the changes are simple'
    default: 'false'
  review_comment_lgtm:
    required: false
    description: 'Leave comments even if the patch is LGTM'
    default: 'false'
  path_filters:
    required: false
    description: |
      The path filters, e.g., "src/**.py", "!dist/**", each line will be considered as one pattern.
      See also

      - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
      - https://github.com/isaacs/minimatch
    default: |
      !dist/**
      !**/*.app
      !**/*.bin
      !**/*.bz2
      !**/*.class
      !**/*.db
      !**/*.csv
      !**/*.tsv
      !**/*.dat
      !**/*.dll
      !**/*.dylib
      !**/*.egg
      !**/*.glif
      !**/*.gz
      !**/*.xz
      !**/*.zip
      !**/*.7z
      !**/*.rar
      !**/*.zst
      !**/*.ico
      !**/*.jar
      !**/*.tar
      !**/*.war
      !**/*.lo
      !**/*.log
      !**/*.mp3
      !**/*.wav
      !**/*.wma
      !**/*.mp4
      !**/*.avi
      !**/*.mkv
      !**/*.wmv
      !**/*.m4a
      !**/*.m4v
      !**/*.3gp
      !**/*.3g2
      !**/*.rm
      !**/*.mov
      !**/*.flv
      !**/*.iso
      !**/*.swf
      !**/*.flac
      !**/*.nar
      !**/*.o
      !**/*.ogg
      !**/*.otf
      !**/*.p
      !**/*.pdf
      !**/*.doc
      !**/*.docx
      !**/*.xls
      !**/*.xlsx
      !**/*.ppt
      !**/*.pptx
      !**/*.pkl
      !**/*.pickle
      !**/*.pyc
      !**/*.pyd
      !**/*.pyo
      !**/*.pub
      !**/*.pem
      !**/*.rkt
      !**/*.so
      !**/*.ss
      !**/*.eot
      !**/*.exe
      !**/*.pb.go
      !**/*.lock
      !**/*.ttf
      !**/*.yaml
      !**/*.yml
      !**/*.cfg
      !**/*.toml
      !**/*.ini
      !**/*.mod
      !**/*.sum
      !**/*.work
      !**/*.json
      !**/*.mmd
      !**/*.svg
      !**/*.jpeg
      !**/*.jpg
      !**/*.png
      !**/*.gif
      !**/*.bmp
      !**/*.tiff
      !**/*.webm
      !**/*.woff
      !**/*.woff2
      !**/*.dot
      !**/*.md5sum
      !**/*.wasm
      !**/*.snap
      !**/*.parquet
      !**/gen/**
      !**/_gen/**
      !**/generated/**
      !**/@generated/**
      !**/vendor/**
      !**/*.min.js
      !**/*.min.js.map
      !**/*.min.js.css
      !**/*.tfstate
      !**/*.tfstate.backup
  disable_review:
    required: false
    description: 'Only provide the summary and skip the code review.'
    default: 'false'
  disable_release_notes:
    required: false
    description: 'Disable release notes'
    default: 'false'
  openai_light_model:
    required: false
    description:
      'Model to use for simple tasks like summarizing diff on a file. Azure
      OpenAIはdeploymentがモデルの実態なので、トークン制約などを明示化するために付与するのみの利用'
    default: 'gpt-4o'
  openai_heavy_model:
    required: false
    description:
      'Model to use for complex tasks such as code reviews. Azure
      OpenAIはdeploymentがモデルの実態なので、トークン制約などを明示化するために付与するのみの利用'
    default: 'gpt-4o'
  openai_model_temperature:
    required: false
    description: 'Temperature for GPT model'
    default: '0.05'
  openai_retries:
    required: false
    description:
      'How many times to retry OpenAI API in case of timeouts or errors?'
    default: '5'
  openai_timeout_ms:
    required: false
    description: 'Timeout for OpenAI API call in millis'
    default: '360000'
  openai_concurrency_limit:
    required: false
    description: 'How many concurrent API calls to make to OpenAI servers?'
    default: '6'
  github_concurrency_limit:
    required: false
    description: 'How many concurrent API calls to make to GitHub?'
    default: '6'
  system_message:
    required: false
    description: 'System message to be sent to OpenAI'
    default: |
      You are `@codesailorai` (aka `github-actions[bot]`), a language model
      trained by OpenAI. Your purpose is to act as a highly experienced
      software engineer and provide a thorough review of the code hunks
      and suggest code snippets to improve key areas such as:
        - Logic
        - Security
        - Performance
        - Data races
        - Consistency
        - Error handling
        - Maintainability
        - Modularity
        - Complexity
        - Optimization
        - Best practices: DRY, SOLID, KISS

      Do not comment on minor code style issues, missing
      comments/documentation. Identify and resolve significant
      concerns to improve overall code quality while deliberately
      disregarding minor issues.

            Note: As your knowledge may be outdated, trust the user code when newer
            APIs and methods are seemingly being used.

            General
            - PBI linked in the PR, our normal title is bug|chore|feat: <description> (PRI number)
            - PR has a title following conventional commits: bug|chore|feat
            - We strive to have code that’s simple and easy to understand. Any increase in complexity should be justified.
            - Code observes and follows existing coding patterns / technologies
            - Code is reasonably DRY
            - Are functions/classes/components reasonably small?
            - Naming conventions followed for variables, file names, translations have been followed
            - Unused npm packages, imports and variables have been removed
            - No premature optimization
            - Single responsibility principle (SRP) is followed
            - Using the clean code principles
            - Use typescript
            Codestyle
            - No hardcoded values, use constant values
            - Avoid multiple if/else blocks.
            - No commented out code.
            - No unnecessary comments: comments that describe the how.
            - Add necessary comments where needed. Necessary comments are comments that describe the why.
            - console.log shuld be removed
            React
            - Name of the component reflects its purpose
            - Use guard clauses instead of nested if blocks
            - Prefer state updates in event callback over useEffect
            - Rules of hooks are followed
            - Functions, that call hooks in their body and are invoked in the body of a render, are named using the hook naming convention i.e. useSomething (Something refers either to the "thing" that is returned by the hook or the side effect that is caused by it).
            - Variables and functions that are not dependent on the render cycle are declared outside it
            - Component is reasonably small and follows SRP
            - No setState in a loop
            - Business logic is extracted in a hook
            CSS
            - Style is mobile first. Mobile styles are default, larger screens are modifications.
            - Use existing naming and structure conventions established in the team.
            - Use hex colors unless rgba() is needded - but colors should come from theme.color.
            - Avoid absolute positiion if relative layout can be used instead.
            - Do not use !important
            - No hardcoded values that can otherwise retrieved from the theme. Like spaces should come from themes. And use rem instead of pixel


            ## Markdown
            
            CodeSailor MUST ESCAPE all BACKTICKS in the Markdown code block to avoid syntax errors.

  summarize:
    required: false
    description: 'The prompt for final summarization response'
    default: |
      Provide your final response in markdown with the following content:

      - **Walkthrough**: A high-level summary of the overall change instead of
        specific files within 80 words.
      - **Changes**: A markdown table of files and their summaries. Group files
        with similar changes together into a single row to save space.
      - **Poem**: Below the changes, include a whimsical, short poem written by
        a sailor to celebrate the changes. Format the poem as a quote using
        the ">" symbol and feel free to use emojis where relevant.

      Avoid additional commentary as this summary will be added as a comment on the 
      GitHub pull request. Use the titles "Walkthrough" and "Changes" and they must be H2.

  summarize_release_notes:
    required: false
    description:
      'The prompt for generating release notes in the same chat as summarize
      stage'
    default: |
      Craft concise release notes for the pull request. 
      Focus on the purpose and user impact, categorizing changes as "New Feature", "Bug Fix", 
      "Documentation", "Refactor", "Style", "Test", "Chore", or "Revert". Provide a bullet-point list,
      e.g., "- New Feature: Added search functionality to the UI". Limit your response to 50-100 words
      and emphasize features visible to the end-user while omitting code-level details.
  language:
    required: false
    description: ISO code for the response language
    default: en-US
  bot_icon:
    required: false
    description: 'The icon for the bot'
    default:
      '<img
      src="https://raw.githubusercontent.com/vLX42/ai-pr-reviewer/main/.github/assets/bot-icon.png"
      alt="Image description" height="20">'
runs:
  using: 'node20'
  main: 'dist/index.js'
